# Created 10/01/2025 by Aline Vernier, LOA

################################################################################
# HOW TO FILL THIS TOML FILE :

# General for all devices :
#   Name : name of device to display in parameter set - General for all devices
#   Address : Address of device driver in TANGO
# Device-specific :
#   Attributes : List of attributes to be fetched from TANGO bus

################################################################################

title = "Tango Devices"

[owner]
name = "Aline Vernier"

[cameras]
    [cameras.oscillator]
    name = 'Osc cam'
    address = 'FE_CAMERA_1/LimaDetector/1'
    # attributes : Image attribute name in TANGO
    attributes = ['image']
    # pixel size in µm
    pixel_size = 2

    [cameras.amplifier]
    name = 'Amp cam'
    address = ''
    # attributes : Image attribute name in TANGO
    attributes = ['image']
    # pixel size in µm
    pixel_size = 2

[analysis]
    [analysis.oscillator]
    name = 'Oscillator beam analysis'
    address = 'FE_CAMERA_1/ImgBeamAnalyzer/1'
    # attributes : Image attribute name in TANGO
    attributes = ['CentroidX', 'CentroidY', 'MaxIntensity',
        'PeakX', 'PeakY', 'VarianceX', 'VarianceY']


[spectrometers]
    [spectrometers.oscillator]
    name = 'Osc spectrum'
    address = 'SY-SPECTRO_1/Spectrometer/FE1'
    # attributes : Attributes of wavelength and intensity axes in TANGO
    attributes = ['lambda', 'intensity']

    [spectrometers.amplifier]
    name = 'Amp spectrum'
    address = ''
    # attributes : Attributes of wavelength and intensity axes in TANGO
    attributes = ['lambda', 'intensity']


    [spectrometers.compressor]
    name = 'comp spectrum'
    address = ''
    # attributes : Attributes of wavelength and intensity axes in TANGO
    attributes = ['lambda', 'intensity']

[energymeters]
    [energymeters.oscillator]
    name = 'Oscillator energy'
    address = ''
    # attributes : Energy attribute name in TANGO
    attributes = ['energy']

    [energymeters.amplifier]
    name = 'Amplifier spectrometer'
    address = 'AMP_EM_1/Energymeter/1'
    # attributes : Energy attribute name in TANGO
    attributes = ['energy_1']
